version: '3'
services:
  rclone:
    image: rclone/rclone
    container_name: rclone_rclone
    restart: always
    command: rcd --rc-web-gui --rc-addr 0.0.0.0:5572 --rc-user admin --rc-pass 123
    ports:
      - "5572:5572"
      - "53682:53682"
    volumes:
      - ./config/rclone:/config/rclone
      - ./logs:/logs
    environment:
      - PHP_TZ=Europe/London
      - PUID=1000
      - PGID=1000